name: fluxpark_env
channels:
  - conda-forge
dependencies:
  - python==3.9.13
  - requests
  - sqlalchemy==1.4.42
  - psycopg2-binary==2.9.2
  - pandas==1.5.1
  - openpyxl==3.0.10
  - fire==0.4.0
  - boto3==1.24.93
  - pyproj
  - gdal==3.3.2
  - scipy==1.9.2
  - numpy==1.23.4
  - statsmodels==0.13.2
  - gstools==1.4.0
  - pip
  - pip:
      - -e .
