name: fluxpark_env
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pandas>=1.5.1
  - openpyxl>=3.0.0
  - gdal>=3.3.2
  - proj
  - libgdal-hdf5
  - libgdal-netcdf
  - scipy>=1.9.2
  - numpy>=1.23.4
  - pip
  - pip:
      - fluxpark
